name: Execute shell script
on:
    push: 
        branches: ["master"]
    workflow_dispatch: 
jobs:
    Checkout:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v4
    Execution:
        needs: Checkout
        runs-on: ubuntu-latest
        steps:
        - name: Code Exection
          run: |
           pwd
           cd ..
           cp hello.sh /home/runner/work/github-actions-demo/github-actions-demo
           sh hello.sh
          
