name: Execute shell script
on:
    push: 
        branches: ["master"]
    workflow_dispatch: 
jobs:
    Checkout:
        runs-on: self-hosted
        steps:
            - name: Code Checkout
              uses: actions/checkout@v4
    Execution:
        needs: Checkout
        runs-on: ubuntu-latest
        steps:
        - name: Code Execution
          run: |
           pwd
           cp /home/runner/work/github-actions-demo/github-actions-demo/hello.sh ~/
           sh ~/hello.sh
          
